name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.2.0
      with:
        hugo-version: 'latest'
    - name: Build
      run: yarn install && yarn build
    - name: Firebase Deploy
      uses: w9jds/firebase-action@develop
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      with:
        args: deploy
    - name: Discord Succeeded
      uses: appleboy/discord-action@0.0.2
      env:
        WEBHOOK_ID: "${{ secrets.DISCORD_WEBHOOK_ID }}"
        WEBHOOK_TOKEN: "${{ secrets.DISCORD_WEBHOOK_TOKEN }}"
        COLOR: "#49C39E"
      with:
        args: "[CI] https://zihao.me Succeeded"
    - name: Discord Failed
      if: failure()
      uses: appleboy/discord-action@0.0.2
      env:
        WEBHOOK_ID: "${{ secrets.DISCORD_WEBHOOK_ID }}"
        WEBHOOK_TOKEN: "${{ secrets.DISCORD_WEBHOOK_TOKEN }}"
        COLOR: "#D40E0D"
      with:
        args: "[CI] https://zihao.me Failed"
