name: Node CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: node install, build, and test
      run: |
        yarn install
      env:
        CI: true
    - name: Discord Succeeded
      uses: appleboy/discord-action@0.0.2
      env:
        WEBHOOK_ID: "${{ secrets.DISCORD_WEBHOOK_ID }}"
        WEBHOOK_TOKEN: "${{ secrets.DISCORD_WEBHOOK_TOKEN }}"
        COLOR: "#49C39E"
      args: "[CI] https://zihao.me Succeeded"
    - name: Discord Failed
      if: failure()
      uses: appleboy/discord-action@0.0.2
      env:
        WEBHOOK_ID: "${{ secrets.DISCORD_WEBHOOK_ID }}"
        WEBHOOK_TOKEN: "${{ secrets.DISCORD_WEBHOOK_TOKEN }}"
        COLOR: "#D40E0D"
      args: "[CI] https://zihao.me Failed"
